Repository sayonarabyee/StackGame, pull requests merged in 2020-07, with the labels that each got.

#3 Feature/sg 2 add di
  .gitignore
  Assets/DependencyInjection.meta
  Assets/DependencyInjection/DefaultStartupInstaller.cs
  Assets/DependencyInjection/DefaultStartupInstaller.cs.meta
  Assets/Interfaces.meta
  Assets/Interfaces/IGameManager.cs
  Assets/Interfaces/IGameManager.cs.meta
  Assets/Plugins.meta
  Assets/Plugins/Editor.meta
  Assets/Plugins/Zenject.meta
  Assets/Scripts/GameManagerScript.cs
  Assets/Scripts/GameManagerScript.cs.meta
  Assets/Scripts/MovingPlatform.cs
  Assets/Services.meta
  Assets/Services/GameManager.cs
  Assets/Services/GameManager.cs.meta
  Packages/manifest.json
  ProjectSettings/EditorSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: enhancement

#5 Feature/sg 2 add di
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameManagerScript.cs
Labels: bug

#11 spawning
  .gitignore
  Assets/DependencyInjection/DefaultStartupInstaller.cs
  Assets/Interfaces/IGameManager.cs
  Assets/Interfaces/IPlatformManager.cs
  Assets/Interfaces/IPlatformManager.cs.meta
  Assets/Plugins/Editor.meta
  Assets/Plugins/Zenject.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameManagerScript.cs
  Assets/Scripts/MovingPlatform.cs
  Assets/Services/GameManager.cs
  Assets/Services/PlatformManager.cs
  Assets/Services/PlatformManager.cs.meta
  ProjectSettings/ProjectVersion.txt
Labels: enhancement, gameplay, mechanic

#12 moved files to src/StackGame.Unity
  Assets/Plugins/Editor.meta
  Assets/Plugins/Zenject.meta
  Assets/Scripts/MainPlatform.cs
  Assets/Scripts/MainPlatform.cs.meta
  Assets/Scripts/MovingPlatform.cs
  src/StackGame.Unity/Assets/DependencyInjection.meta
  src/StackGame.Unity/Assets/DependencyInjection/DefaultStartupInstaller.cs
  src/StackGame.Unity/Assets/DependencyInjection/DefaultStartupInstaller.cs.meta
  src/StackGame.Unity/Assets/Interfaces.meta
  src/StackGame.Unity/Assets/Interfaces/IPlatformManager.cs
  src/StackGame.Unity/Assets/Interfaces/IPlatformManager.cs.meta
  src/StackGame.Unity/Assets/Plugins.meta
  src/StackGame.Unity/Assets/Prefabs.meta
  src/StackGame.Unity/Assets/Prefabs/MovingPlatform.prefab
  src/StackGame.Unity/Assets/Prefabs/MovingPlatform.prefab.meta
  src/StackGame.Unity/Assets/Scenes.meta
  src/StackGame.Unity/Assets/Scenes/MainScene.unity
  src/StackGame.Unity/Assets/Scenes/MainScene.unity.meta
  src/StackGame.Unity/Assets/Scripts.meta
  src/StackGame.Unity/Assets/Scripts/GameManager.cs
  src/StackGame.Unity/Assets/Scripts/GameManager.cs.meta
  src/StackGame.Unity/Assets/Scripts/MovingPlatform.cs
  src/StackGame.Unity/Assets/Scripts/MovingPlatform.cs.meta
  src/StackGame.Unity/Assets/Services.meta
  src/StackGame.Unity/Assets/Services/PlatformManager.cs
  src/StackGame.Unity/Assets/Services/PlatformManager.cs.meta
  src/StackGame.Unity/Packages/manifest.json
  src/StackGame.Unity/ProjectSettings/AudioManager.asset
  src/StackGame.Unity/ProjectSettings/ClusterInputManager.asset
  src/StackGame.Unity/ProjectSettings/DynamicsManager.asset
  src/StackGame.Unity/ProjectSettings/EditorBuildSettings.asset
  src/StackGame.Unity/ProjectSettings/EditorSettings.asset
  src/StackGame.Unity/ProjectSettings/GraphicsSettings.asset
  src/StackGame.Unity/ProjectSettings/InputManager.asset
  src/StackGame.Unity/ProjectSettings/NavMeshAreas.asset
  src/StackGame.Unity/ProjectSettings/NetworkManager.asset
  src/StackGame.Unity/ProjectSettings/Physics2DSettings.asset
  src/StackGame.Unity/ProjectSettings/PresetManager.asset
  src/StackGame.Unity/ProjectSettings/ProjectSettings.asset
  src/StackGame.Unity/ProjectSettings/ProjectVersion.txt
  src/StackGame.Unity/ProjectSettings/QualitySettings.asset
  src/StackGame.Unity/ProjectSettings/TagManager.asset
  src/StackGame.Unity/ProjectSettings/TimeManager.asset
  src/StackGame.Unity/ProjectSettings/UnityConnectSettings.asset
  src/StackGame.Unity/ProjectSettings/VFXManager.asset
Labels: enhancement

#21 changed spawn position and speed vector calculating
  src/StackGame.Unity/Assets/Scripts/MovingPlatform.cs
  src/StackGame.Unity/Assets/Services/PlatformManager.cs
Labels: bug, game, mechanic

#15 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#26 Create activation.yml
  .github/activation.yml
Labels: enhancement

#28 Feature/sg 18 game over
  src/StackGame.Unity/Assets/Constants.cs
  src/StackGame.Unity/Assets/Constants.cs.meta
  src/StackGame.Unity/Assets/Interfaces/IPlatformManager.cs
  src/StackGame.Unity/Assets/Resources/Prefabs/GameManager.prefab
  src/StackGame.Unity/Assets/Resources/Prefabs/MovingPlatform.prefab
  src/StackGame.Unity/Assets/Scenes/MainScene.unity
  src/StackGame.Unity/Assets/Scripts/GameManager.cs
  src/StackGame.Unity/Assets/Scripts/MovingPlatform.cs
  src/StackGame.Unity/Assets/Services/PlatformManager.cs
  src/StackGame.Unity/Assets/Tests/EditorModeTests/GameManagerTests.cs
  src/StackGame.Unity/Assets/Tests/EditorModeTests/PlatformManagerTests.cs
  src/StackGame.Unity/Assets/Tests/EditorModeTests/TestClassBase.cs
  src/StackGame.Unity/Assets/Tests/EditorModeTests/TestClassBase.cs.meta
  src/StackGame.Unity/Assets/Tests/PlayModeTests/GameManagerTests.cs
  src/StackGame.Unity/Assets/Tests/PlayModeTests/GameManagerTests.cs.meta
Labels: design, enhancement, mechanic

#31 added camera movement
  src/StackGame.Unity/Assets/Constants.cs
  src/StackGame.Unity/Assets/Interfaces/ICameraManager.cs
  src/StackGame.Unity/Assets/Interfaces/ICameraManager.cs.meta
  src/StackGame.Unity/Assets/Resources/Prefabs/GameManager.prefab
  src/StackGame.Unity/Assets/Scenes/MainScene.unity
  src/StackGame.Unity/Assets/Scripts/GameManager.cs
  src/StackGame.Unity/Assets/Services/CameraManager.cs
  src/StackGame.Unity/Assets/Services/CameraManager.cs.meta
  src/StackGame.Unity/Assets/Tests/PlayModeTests/GameManagerTests.cs
Labels: enhancement, game, mechanic
